async(page)=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.setViewportSize({width:1100,height:800});
  await page.goto('http://127.0.0.1:4187/test/fixtures/panel-system.html');
  await page.waitForFunction(()=>Boolean(window.panelDemo));
  const panel=page.frameLocator('iframe[title="panel"]'),ball=page.frameLocator('iframe[title="ball"]');
  await page.getByRole('button',{name:'开始任务',exact:true}).click();
  await page.waitForFunction(()=>panelDemo.frames.ball.contentWindow.__metaBotDebug.getExpressionState().activity?.name==='performance_companion_work_open');
  await panel.getByRole('button',{name:'陪伴工具',exact:true}).click();
  await panel.locator('.companion-tools').waitFor({state:'visible'});
  await panel.getByRole('textbox',{name:'完成便签'}).fill('完成后检查单元测试');
  await panel.getByRole('button',{name:'夹好便签',exact:true}).click();
  await page.waitForFunction(()=>panelDemo.stored['companion.json']?.notes.length===1);
  await panel.getByRole('button',{name:'插旗关注',exact:true}).click();
  await page.waitForFunction(()=>!!panelDemo.stored['companion.json'].pinned);
  await panel.getByRole('button',{name:'纸飞机 · 复制链接',exact:true}).click();
  if(await panel.locator('#companionFeedback').textContent())throw Error('Copy failed');
  await panel.getByRole('button',{name:'生活物件',exact:true}).click();
  for(const space of ['stool','mat','lamp','box','plant','tray']){
    await panel.locator('[data-space="'+space+'"]').click();
    await ball.locator('.companion-space[data-space="'+space+'"]').waitFor({state:'visible'});
  }
  await panel.getByRole('button',{name:'浇水',exact:true}).click();
  await page.waitForFunction(()=>panelDemo.stored['companion.json'].wateredAt>0);
  await panel.getByRole('button',{name:'陪工道具',exact:true}).click();
  await panel.getByRole('button',{name:'25 分钟',exact:true}).click();
  await ball.locator('.companion-space.is-lit').waitFor();
  await panel.getByRole('button',{name:'结束专注',exact:true}).click();
  await page.waitForFunction(()=>panelDemo.bot().companion.state.focusUntil===0);
  await panel.locator('#timerMinutes').fill('1');await panel.getByRole('button',{name:'翻转沙漏',exact:true}).click();
  await page.waitForFunction(()=>!!panelDemo.stored['companion.json'].timer);
  await page.evaluate(()=>{panelDemo.faults.store='companion.json';panelDemo.bot().companion.now=()=>Date.now()+61000;});
  await panel.locator('.board-card').filter({hasText:'沙漏计时结束'}).waitFor();
  await page.waitForFunction(()=>panelDemo.stored['companion.json'].timer===null&&panelDemo.stored['companion.json'].alerts.some(a=>a.title==='沙漏计时结束'));
  await page.evaluate(()=>{panelDemo.bot().companion.now=Date.now;});
  await panel.locator('.board-card').filter({hasText:'沙漏计时结束'}).getByRole('button',{name:'确认提醒',exact:true}).click();
  await page.getByRole('button',{name:'完成任务',exact:true}).click();
  await panel.locator('.board-card').filter({hasText:'便签：完成后检查单元测试'}).waitFor();
  await panel.locator('[data-status="completed"]').getByRole('button',{name:'查看任务',exact:true}).click();
  await page.waitForFunction(()=>panelDemo.bot().inbox.items.size===0&&panelDemo.stored['companion.json'].history.length===1);
  await panel.locator('.board-card').filter({hasText:'便签：'}).getByRole('button',{name:'确认提醒',exact:true}).click();
  // A failed save must not falsely pin a preference in the UI or in memory.
  const previous=await page.evaluate(()=>panelDemo.bot().companion.state.space);
  await panel.getByRole('button',{name:'生活物件',exact:true}).click();
  await page.evaluate(()=>panelDemo.faults.store='companion.json');
  await panel.locator('[data-space="box"]').click();
  await panel.locator('#companionFeedback').filter({hasText:'模拟保存失败'}).waitFor();
  if(await page.evaluate(()=>panelDemo.bot().companion.state.space)!==previous)throw Error('Failed save changed state');
  await panel.locator('[data-space="box"]').click();
  const ids=await panel.locator('#companionGameSelect option').evaluateAll(nodes=>nodes.map(n=>n.value));
  await panel.getByRole('button',{name:'短时互动',exact:true}).click();
  if(ids.length!==12)throw Error('Missing games');
  for(const id of ids){
    await panel.locator('#companionGameSelect').selectOption(id);
    await panel.getByRole('button',{name:'开始',exact:true}).click();
    await page.waitForFunction(id=>panelDemo.bot().companion.game?.id===id,id);
    await panel.locator('#companionGame svg').waitFor({state:'visible'});
    if(await panel.locator('#companionGame svg').evaluate(e=>e.children.length)<1)throw Error('Empty game '+id);
    await panel.locator('#companionGame').screenshot({path:'output/playwright/companion-game-'+id+'.png'});
    await panel.getByRole('button',{name:'收好',exact:true}).click();
    await page.waitForFunction(()=>panelDemo.bot().companion.game===null);
  }
  await panel.locator('#companionGameSelect').selectOption('catch');await panel.getByRole('button',{name:'开始',exact:true}).click();
  await page.waitForFunction(()=>panelDemo.bot().companion.game?.id==='catch');
  await panel.locator('#companionGame').scrollIntoViewIfNeeded();
  const target=await page.evaluate(()=>panelDemo.bot().companion.gameView().target);
  const r=await panel.locator('#companionGame').boundingBox();await page.mouse.click(r.x+r.width*target/100,r.y+r.height/2);
  await page.waitForFunction(()=>panelDemo.bot().companion.game?.score===1);
  await page.getByRole('button',{name:'开始任务',exact:true}).click();
  await page.waitForFunction(()=>panelDemo.bot().companion.game===null);
  await panel.locator('#companionGameSelect').selectOption('water');await panel.getByRole('button',{name:'开始',exact:true}).click();
  await panel.locator('#companionGame').focus();await page.keyboard.down('Space');await page.waitForTimeout(1500);await page.keyboard.up('Space');
  await page.waitForFunction(()=>panelDemo.bot().companion.game?.score===1);
  await panel.getByRole('button',{name:'连接与同步',exact:true}).click();
  await page.waitForFunction(()=>panelDemo.bot().companion.game===null);
  await panel.getByRole('button',{name:'陪伴',exact:true}).click();
  await panel.getByRole('button',{name:'生活物件',exact:true}).click();
  await panel.locator('[data-space="plant"]').click();
  await panel.locator('#diagnostics').evaluate(e=>{e.scrollTop=0;});
  await panel.locator('#panel').screenshot({path:'output/playwright/companion-tools.png'});
  await page.locator('iframe[title="ball"]').screenshot({path:'output/playwright/companion-space.png'});
  await page.evaluate(()=>{for(const id of ['panel','ball'])panelDemo.frames[id].srcdoc=panelDemo.frames[id].srcdoc;});
  await page.waitForFunction(()=>panelDemo.bot()?.companion.state.space==='plant'&&panelDemo.bot().companion.state.history.length===1);
  if(errors.length)throw Error(errors.join('\n'));
  return {workOpening:true,notes:true,focus:true,timer:true,history:true,pin:true,spaces:6,games:12,pointerScoring:true,keyboardScoring:true,taskInterrupts:true,saveRollback:true,restart:true,errors};
}
