async(page)=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.setViewportSize({width:1100,height:780});
  await page.goto('http://127.0.0.1:4187/test/fixtures/panel-system.html');
  await page.waitForFunction(()=>Boolean(window.panelDemo));
  const panel=page.frameLocator('iframe[title="panel"]');
  await page.getByRole('button',{name:'开始任务',exact:true}).click();
  await panel.locator('[data-status="running"]').waitFor({state:'visible'});
  await page.getByRole('button',{name:'暂停任务',exact:true}).click();
  await panel.locator('[data-status="paused"]').waitFor({state:'visible'});
  await page.getByRole('button',{name:'继续任务',exact:true}).click();
  await panel.locator('[data-status="running"]').waitFor({state:'visible'});
  await page.getByRole('button',{name:'任务失败',exact:true}).click();
  await panel.locator('[data-status="failed"]').waitFor({state:'visible'});
  await page.waitForTimeout(4300);
  if(!await page.evaluate(()=>panelDemo.windows.panel.visible))throw Error('Failure expired');
  await panel.getByRole('button',{name:'确认提醒',exact:true}).click();
  await page.waitForFunction(()=>!panelDemo.windows.panel.visible);
  await page.getByRole('button',{name:'开始任务',exact:true}).click();
  await page.getByRole('button',{name:'停止任务',exact:true}).click();
  await panel.locator('[data-status="stopped"]').waitFor({state:'visible'});
  await panel.getByRole('button',{name:'确认提醒',exact:true}).click();
  await page.getByRole('button',{name:'开始任务',exact:true}).click();
  await page.getByRole('button',{name:'完成任务',exact:true}).click();
  await panel.locator('[data-status="completed"]').waitFor({state:'visible'});
  await page.evaluate(()=>{panelDemo.faults.open=true;});
  await panel.getByRole('button',{name:'查看任务',exact:true}).click();
  await panel.locator('.board-action-error').filter({hasText:'模拟打开失败'}).waitFor({state:'visible'});
  await page.evaluate(()=>{panelDemo.faults.store='completion-inbox.json';});
  await panel.getByRole('button',{name:'查看任务',exact:true}).click();
  await panel.locator('.board-action-error').filter({hasText:'模拟保存失败'}).waitFor({state:'visible'});
  if(!await page.evaluate(()=>panelDemo.bot().inbox.items.size===1&&panelDemo.stored['completion-inbox.json'].length===1))throw Error('Failure discarded completion');
  if(!await panel.getByRole('button',{name:'确认提醒',exact:true}).isEnabled())throw Error('Failed action left controls disabled');
  await page.setViewportSize({width:390,height:740});
  await page.evaluate(()=>panelDemo.resize(360,420));
  await page.waitForTimeout(400);
  const bounds=await page.evaluate(()=>panelDemo.windows.panel);
  if(bounds.x<0||bounds.x+bounds.width>360||bounds.y<0||bounds.y+bounds.height>420)throw Error('Small work area overflow '+JSON.stringify(bounds));
  await page.locator('#stage').screenshot({path:'output/playwright/unified-board-small-area.png'});
  const controls=await panel.getByRole('button',{name:'确认提醒',exact:true}).evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;});
  if(!controls)throw Error('Confirmation clipped');
  const cardFits=await panel.locator('.board-card').evaluate(el=>{const r=el.getBoundingClientRect(),s=el.parentElement.parentElement.getBoundingClientRect();return r.top>=s.top&&r.bottom<=s.bottom;});
  if(!cardFits)throw Error('Error feedback clipped the task card');
  await panel.getByRole('button',{name:'查看任务',exact:true}).click();
  await page.waitForFunction(()=>panelDemo.bot().inbox.items.size===0&&!panelDemo.windows.panel.visible);
  if(errors.length)throw Error(errors.join('\n'));
  return {pauseResume:true,failureRetained:true,stoppedAcknowledged:true,openFailureRetained:true,persistenceFailureRetained:true,retry:true,smallWorkArea:true,errors};
}
